# Generated by Django 5.1.4 on 2025-01-09 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='取引金額'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='date',
            field=models.DateField(verbose_name='取引日'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='name',
            field=models.CharField(max_length=100, verbose_name='取引名'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('income', '支出'), ('expense', '収入')], max_length=10, verbose_name='取引種別'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザー'),
        ),
    ]
